<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>26、Promise对象的catch方法</title>
</head>

<body>
    <script>
        // catch方法可以捕获then链式调用中任意一环出现的错误。
        const p = new Promise((resolve, reject) => {
            setTimeout(() => {
                reject('失败的Promise')
            }, 1000)
        })

        // 使用then的第二个参数捕获错误
        // p.then((res) => { }, (err) => {
        //     console.warn(err)
        // })

        // 使用catch来单独捕获错误
        p.catch((err) => {
            console.log(err)
        })
    </script>
</body>

</html>